### ISSUE TITLE
ember-cli deprecation warning: overriding init without calling this.super

### ISSUE THREAD

**Issue by jming422** [nolanlawson/ember-pouch#128] opened 2016-06-20 02:39 UTC
On a fresh project created with ember-cli, after doing `ember install ember-pouch`, this deprecation warning appears:
```
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-pouch`
    at Function.Addon.lookup (/path/to/project/node_modules/ember-cli/lib/models/addon.js:896:27)
```
If you look at ember-cli/core-object/pull/37 you'll see an updated wording of this warning which I found much more clear:
```
The addon `ember-pouch` is overriding init without calling this._super. 
          This behaviour is deprecated. 
          This means that addon's author needs to update it calling `this._super.init && this._super.init.apply(this, arguments)` 
          and release a new version. 
          Do not worry, ember-cli is working normally.
```

ember-pouch still functions the same in every other way, but it's a bit annoying to see that warning every time I use any ember-cli command.

**Comment by fredguth** [comment] 2016-06-20 21:43
I have the same issue.  I am not sure, but I think this prevents me to generate pouch-model:
```
$ ember g pouch-model mymodel
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-pouch`
    at Function.Addon.lookup (/Users/fredguth/Code/julia/node_modules/ember-cli/lib/models/addon.js:896:27)
Cannot find module 'ember-cli/blueprints/model'
Error: Cannot find module 'ember-cli/blueprints/model'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/fredguth/Code/julia/node_modules/ember-pouch/blueprints/pouch-model/index.js:1:92)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

**Comment by fsmanuel** [comment] 2016-06-20 22:16
@fredguth I'm not sure if the deprecation is responsible for your problem. Seems like `Error: Cannot find module 'ember-cli/blueprints/model'` is the cause for it. I think I remember that something with the blueprints in ember-cli has changed. They no longer maintain them and moved them into ember-data.

**Comment by fsmanuel** [comment] 2016-06-20 22:30
@mattmarcum or @backspace is one of you up to date with the changes in ember-cli and ember-data?
Maybe we just have to change that [line](https://github.com/nolanlawson/ember-pouch/blob/master/blueprints/pouch-model/index.js#L1):
```js
// from
var EmberCliModelBlueprint = require('ember-cli/blueprints/model');
// to
var EmberCliModelBlueprint = require('ember-data/blueprints/model');
```

**Comment by nolanlawson** [comment] 2016-06-21 00:36
fixed in #129, thanks @fsmanuel

**Closed by nolanlawson** 2016-06-21 00:36 UTC

**Comment by fredguth** [comment] 2016-06-21 10:49
thanks @fsmanuel and @nolanlawson

**Comment by fsmanuel** [comment] 2016-06-21 11:17
@fredguth if your problem still exists you should open a new issue for the blueprint fix
